# Generated by Django 5.1.13 on 2025-11-05 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("status", models.CharField(default="pending", max_length=32)),
                ("location", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("status", models.CharField(default="unknown", max_length=32)),
                ("message", models.TextField(blank=True)),
                ("last_checked", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=24)),
                (
                    "captured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
            },
        ),
    ]
